version: "3"

services:
  onlyoffice:
      image: "onlyoffice/documentserver"
      container_name: inethi-onlyoffice
      tty: true
      restart: always

      labels:
        - "traefik.http.routers.onlyoffice.middlewares=onlyoffice-headers"
        - "traefik.http.middlewares.onlyoffice-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.onlyoffice-headers.headers.accessControlAllowList=*"
        - "traefik.enable=true"
        - "traefik.http.routers.onlyoffice.rule=Host(`${TRAEFIK_API_RULE_HOST}.${inethiDN}`)"
        - "traefik.http.routers.onlyoffice.entrypoints=${TRAEFIK_ENTRYPOINT}"
        #- "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*" 
        #- "traefik.http.routers.service.middlewares=serviceheaders"
        

networks:
  default:
    external:
      name: "${INETHI_NETWORK}"

      